export const ADD_POKEMONS = 'ADD_POKEMONS'

export const LIKE_POKEMON = 'LIKE_POKEMON'

export const SEARCH_POKEMON = 'SEARCH_POKEMON'

export const FETCH_POKEMON = 'FETCH_POKEMON'

export const CAPTURE_POKEMON = 'CAPTURE_POKEMON'

export const LOADING_POKEDEX_POKEMONS = 'LOADING_POKEDEX_POKEMONS'
